databases:
  - name: alx_backend_securitydb
    plan: free
    databaseName: alx_backend_security
    user: alx_backend_security

services:
  - type: web
    plan: free
    name: alx_backend_security
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alx_backend_security db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4