services:
  - type: web
    name: alx-backend-security-web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn alx_backend_security.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: alx_backend_security.settings
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        sync: false

  - type: worker
    name: alx-backend-security-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A alx_backend_security worker --loglevel=info
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: alx_backend_security.settings
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        sync: false

databases:
  - name: alx-backend-db
    databaseName: alx_backend_security
    user: alx_backend_user
